export const routes = [
  { path: "/ops/am/home", workspace: "ops", roles: ["AM"], nav: "我的执行首页", load: () => import("./pages/ops/amHome.js") },
  { path: "/ops/cm/home", workspace: "ops", roles: ["CM"], nav: "CM 执行首页", load: () => import("./pages/ops/cmHome.js") },
  { path: "/ops/ca/home", workspace: "ops", roles: ["CA"], nav: "CA 签署首页", load: () => import("./pages/ops/caHome.js") },
  { path: "/ops/contracts/intake", workspace: "ops", roles: ["AM"], nav: "合同登记与申请", load: () => import("./pages/ops/contractIntake.js") },
  { path: "/ops/contracts/tracking", workspace: "ops", roles: ["CM"], nav: "合同跟进", load: () => import("./pages/ops/contractTracking.js") },
  { path: "/ops/contracts/tracking", workspace: "ops", roles: ["AM", "CA"], nav: "合同进度追踪", load: () => import("./pages/ops/contractTracking.js") },
  { path: "/ops/contracts/tracking/detail", workspace: "ops", roles: ["AM", "CM", "CA"], nav: "合同进度详情", hiddenNav: true, load: () => import("./pages/ops/contractTrackingDetail.js") },
  { path: "/ops/contracts/review-queue", workspace: "ops", roles: ["CA"], nav: "合同审核队列", load: () => import("./pages/ops/contractReviewQueue.js") },
  { path: "/ops/billing/execution", workspace: "ops", roles: ["CM"], nav: "开票登记", load: () => import("./pages/ops/billingExecution.js") },
  { path: "/ops/billing/records", workspace: "ops", roles: ["CM"], nav: "开票记录", load: () => import("./pages/ops/billingRecords.js") },
  { path: "/ops/receivables/balances", workspace: "ops", roles: ["AM", "CM", "CA"], nav: "应收账款", load: () => import("./pages/ops/receivableBalances.js") },
  { path: "/ops/billing/plan", workspace: "ops", roles: ["CM"], nav: "开票计划", load: () => import("./pages/ops/billingPlan.js") },
  { path: "/ops/billing/calendar", workspace: "ops", roles: ["CM"], nav: "开票日历", load: () => import("./pages/ops/billingCalendar.js") },
  { path: "/ops/billing/tasks", workspace: "ops", roles: ["CM"], nav: "开票事项", load: () => import("./pages/ops/billingTasks.js") },
  { path: "/ops/billing/tasks/detail", workspace: "ops", roles: ["CM"], nav: "开票事项详情", hiddenNav: true, load: () => import("./pages/ops/billingTaskDetail.js") },

  { path: "/plan/scp/home", workspace: "plan", roles: ["SCP"], nav: "SCP 计划首页", load: () => import("./pages/plan/scpHome.js") },
  { path: "/plan/ca/home", workspace: "plan", roles: ["CA"], nav: "CA 管理首页", load: () => import("./pages/plan/caReviewHome.js") },
  { path: "/plan/contracts", workspace: "plan", roles: ["SCP", "CA"], nav: "合同计划", load: () => import("./pages/plan/contractPlanning.js") },
  { path: "/plan/billing", workspace: "plan", roles: ["SCP", "CA", "CM"], nav: "开票计划复盘", load: () => import("./pages/plan/billingPlanning.js") },
  { path: "/plan/targets", workspace: "plan", roles: ["SCP", "CA"], nav: "目标分解", load: () => import("./pages/plan/targetAllocation.js") },
  { path: "/plan/cost-coverage", workspace: "plan", roles: ["SCP", "CA"], nav: "成本覆盖", load: () => import("./pages/plan/costCoverage.js") },
  { path: "/plan/adjustments", workspace: "plan", roles: ["SCP", "CA"], nav: "调整申请", load: () => import("./pages/plan/adjustments.js") },
  { path: "/plan/review-dashboard", workspace: "plan", roles: ["SCP", "CA"], nav: "管理复盘看板", load: () => import("./pages/plan/reviewDashboard.js") },
];
